"""Run records on disk, and the page each platform's records render to.

A recorded run is one JSON file, `docs/clients/<platform>/<client>/<run id>.json`, written
only from a clean checkout, so that its version names exactly the code that ran. The page
`docs/clients/<platform>.md` is derived from those files and nothing else; it is never
edited by hand, and `report --check` fails when it no longer matches them.
"""
from __future__ import annotations

import json
from pathlib import Path

from tvemu.platforms import platform_descriptor

from .model import ClientSpec, client_specs

STATUS = {"ok": "ok", "fail": "**fail**", "not-offered": "not offered", "known-gap": "known gap",
          "known-failure": "known failure"}
GENERATED = ("<!-- Generated by `python -m tvemu.clients report` from the run records beside "
             "this page. Rerun a client or edit its client.toml; never edit this file. -->")


def records_dir(root: Path, platform_id: str, client: str = "") -> Path:
    base = root / "docs" / "clients" / platform_id
    return base / client if client else base


def page_path(root: Path, platform_id: str) -> Path:
    return root / "docs" / "clients" / f"{platform_id}.md"


def write_record(root: Path, record: dict) -> Path:
    directory = records_dir(root, record["platform"], record["client"]["name"])
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{record['run_id']}.json"
    path.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def read_records(root: Path, spec: ClientSpec) -> list[dict]:
    directory = records_dir(root, spec.platform, spec.name)
    if not directory.is_dir():
        return []
    records = [json.loads(path.read_text(encoding="utf-8"))
               for path in directory.glob("*.json")]
    return sorted(records, key=lambda record: record["run_id"], reverse=True)


def _client_version(record: dict) -> str:
    client = record["client"]
    version = client.get("version") or client.get("requested") or ""
    return f"{version} (`{client['commit'][:7]}`)" if client.get("commit") else version


def _emulator(record: dict) -> str:
    emulator = record["emulator"]
    return emulator.get("version") or "?"


def _runtime(record: dict) -> str:
    runtime = record["runtime"]
    # Records before the field existed ran every binding on the emulator's own Python.
    return runtime.get("client") or f"Python {runtime['python']}"


def _client_section(spec: ClientSpec, records: list[dict]) -> list[str]:
    lines = [f"## {spec.name}", "",
             f"{spec.summary} · [upstream]({spec.upstream}) · licence {spec.license} · "
             f"last green `{spec.last_green or 'none yet'}`", ""]
    if not records:
        return [*lines, "Not run yet.", "", *_declarations(spec)]
    lines += ["| Run | Client | Emulator | Runtime | Verdict |", "|---|---|---|---|---|"]
    for record in records:
        lines.append(f"| {record['started_at'][:10]} | {_client_version(record)} | "
                     f"{_emulator(record)} | {_runtime(record)} | "
                     f"{'pass' if record['verdict'] == 'pass' else '**fail**'} |")
    latest = records[0]
    profiles = latest["profiles"]
    lines += ["", f"### Latest run, step by step ({latest['started_at'][:10]})", "",
              "| Step | Action | " + " | ".join(f"`{p['profile']}`" for p in profiles) + " |",
              "|---|---|" + "---|" * len(profiles)]
    order: list[tuple[str, str]] = []
    for profile in profiles:
        for step in profile["steps"]:
            if (step["name"], step["action"]) not in order:
                order.append((step["name"], step["action"]))
    for name, action in order:
        cells = []
        for profile in profiles:
            status = next((step["status"] for step in profile["steps"] if step["name"] == name), "")
            cells.append(STATUS.get(status, status or "—"))
        lines.append(f"| {name} | {action} | " + " | ".join(cells) + " |")
    problems = [(profile["profile"], problem) for profile in profiles
                for problem in profile["problems"]]
    if problems or latest.get("stale_gaps"):
        lines += ["", "Problems in the latest run:", ""]
        lines += [f"- `{profile}`: {problem}" for profile, problem in problems]
        lines += [f"- declared gap never met, stale: `{operation}`"
                  for operation in latest.get("stale_gaps") or []]
    return [*lines, "", *_declarations(spec)]


def _declarations(spec: ClientSpec) -> list[str]:
    lines: list[str] = []
    if spec.gaps:
        lines += ["### Known gaps", "",
                  "Requests this client sends that no capture answers. The emulator refuses "
                  "them rather than invent an answer.", ""]
        lines += [f"- `{gap.operation}`{_scope(gap.profiles)}: {gap.reason}" for gap in spec.gaps]
    if spec.known_failures:
        lines += [*([""] if lines else []), "### Known failures", "",
                  "Steps the emulator answers, but not as this client expects, for a reason "
                  "already understood. Each one is still a failure; it is listed so a run can "
                  "tell it from a new one.", ""]
        lines += [f"- {entry.step}{_scope(entry.profiles)}: {entry.reason}"
                  for entry in spec.known_failures]
    return [*lines, ""]


def _scope(profiles: tuple[str, ...]) -> str:
    return f" (only `{'`, `'.join(profiles)}`)" if profiles else ""


def render(root: Path, platform_id: str) -> str | None:
    specs = [spec for spec in client_specs((platform_id,))]
    if not specs:
        return None
    name = platform_descriptor(platform_id).display_name
    lines = [f"# Open-source clients: {name}", "", GENERATED, "",
             f"Upstream clients for {name}, installed in isolation and run against the emulator. "
             "What a run establishes, and what it does not: "
             "[Open-source clients](../open-source-clients.md).", ""]
    records = {spec.key: read_records(root, spec) for spec in specs}
    if len(specs) > 1:
        lines += ["| Client | Installed from | Last green | Latest recorded run |", "|---|---|---|---|"]
        for spec in specs:
            latest = records[spec.key][0] if records[spec.key] else None
            run = (f"{latest['started_at'][:10]}, "
                   f"{'pass' if latest['verdict'] == 'pass' else '**fail**'}") if latest else "none"
            green = spec.last_green[:12] if spec.install == "git" else spec.last_green
            lines.append(f"| [{spec.name}](#{spec.name}) | {spec.install} | `{green or '-'}` | {run} |")
        lines.append("")
    for spec in specs:
        lines += _client_section(spec, records[spec.key])
    return "\n".join(lines).rstrip() + "\n"


def pages(root: Path) -> dict[Path, str]:
    """Every page this build's client declarations render to."""
    rendered = {}
    for platform_id in sorted({spec.platform for spec in client_specs()}):
        text = render(root, platform_id)
        if text is not None:
            rendered[page_path(root, platform_id)] = text
    return rendered
