#!/usr/bin/env python3
"""Write each television's test report: its unit tests, replay conformance and contract.

    python tools/test_reports.py            # every platform this tree runs
    python tools/test_reports.py roku       # one
    python tools/test_reports.py --check    # every catalogued television has a current report

A report is a record of a run, like an open-source client run: it is written only from a clean
source tree and names the emulator by version, which the published build shares. Reports ship
for every television, the ones a build does not include too; the tests themselves ship only
with the platform. These are the project's own checks, never validation: a television is
validated only by a session with a real app (docs/manual-validation.md).
"""
from __future__ import annotations

import argparse
import io
import json
import os
import platform as host
import re
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from tvemu.clients.runner import emulator_identity  # noqa: E402
from tvemu.platforms import platform_descriptor, platform_ids  # noqa: E402
from tvemu.platforms.catalogue import catalogue_entries  # noqa: E402
from tvemu.platforms.common import report as contract  # noqa: E402

REPORTS = ROOT / "docs" / "tests"
GENERATED = ("<!-- Generated by `python tools/test_reports.py` from a run on a clean source "
             "tree. Rerun it; never edit this file. -->")
VERSION_LINE = re.compile(r"^Emulator \*\*(?P<version>[^*]+)\*\*", re.MULTILINE)


def page(platform_id: str) -> Path:
    return REPORTS / f"{platform_id}.md"


# -- the three checks -------------------------------------------------------------------------

def unit_tests(platform_id: str) -> dict:
    """The platform's own test files, run in this process, counted per test class."""
    # Exactly as the gate discovers them (`-s tests`), so a test that imports its neighbours
    # by bare name runs here as it runs there.
    suite = unittest.TestLoader().discover(str(ROOT / "tests"), pattern=f"test_{platform_id}*.py")
    tests: list[tuple[str, str, str]] = []         # (id, class, module), read before running:
                                                    # a suite lets go of each test it has run

    def walk(item):
        if isinstance(item, unittest.TestSuite):
            for child in item:
                walk(child)
        else:
            tests.append((item.id(), type(item).__name__, type(item).__module__))

    walk(suite)
    result = unittest.TextTestRunner(stream=io.StringIO(), verbosity=0).run(suite)
    failed = {test.id() for test, _ in (*result.failures, *result.errors)}
    skipped = {test.id() for test, _ in result.skipped}
    classes: dict[str, dict] = {}
    files: set[str] = set()
    for test_id, cls, module in tests:
        if module.startswith("unittest."):           # a module that failed to import
            failed.add(test_id)
            continue
        files.add(f"tests/{module.split('.')[-1]}.py")
        entry = classes.setdefault(cls, {"tests": 0, "passed": 0, "skipped": 0})
        entry["tests"] += 1
        if test_id in skipped:
            entry["skipped"] += 1
        elif test_id not in failed:
            entry["passed"] += 1
    return {"files": sorted(files), "run": result.testsRun, "failed": len(failed),
            "skipped": len(skipped), "classes": classes}


def conformance(platform_id: str) -> dict:
    with tempfile.TemporaryDirectory() as temporary:
        report = Path(temporary) / "report.json"
        subprocess.run([sys.executable, "-m", "tvemu.conformance", "--platform", platform_id,
                        "--json-report", str(report)], cwd=ROOT, capture_output=True,
                       env={**os.environ, "PYTHONPATH": str(ROOT / "src")}, check=False)
        return json.loads(report.read_text(encoding="utf-8"))


def contract_check(platform_id: str) -> list[str] | None:
    surface = contract.surface_of(platform_id)
    return None if surface is None else contract.contract_problems(platform_id, surface)


# -- the page ---------------------------------------------------------------------------------

def render(platform_id: str, version: str) -> str:
    name = platform_descriptor(platform_id).display_name
    started = datetime.now(timezone.utc)
    units, replays, problems = unit_tests(platform_id), conformance(platform_id), contract_check(platform_id)
    totals = replays["totals"]
    lines = [f"# Test report: {name}", "", GENERATED, "",
             f"Emulator **{version}** · {started:%Y-%m-%d} · Python {host.python_version()} · "
             "run on a clean source tree.", "",
             "The project's own checks of this television: a byte-for-byte replay of every "
             "captured request, the unit tests of its adapter, and its contract held to the "
             "captures. They are not validation, which only a session with a real app gives "
             "([ledger](../manual-validation.md)); open-source clients are reported apart "
             "([clients](../open-source-clients.md)).", "",
             "## Replay conformance", "",
             "Each profile's captured client traffic is sent through the real listeners and the "
             "answers compared with the capture byte for byte.", "",
             "| Profile | Cases passed | Replays verified | Uncovered |", "|---|---|---|---|"]
    by_profile: dict[str, dict] = {}
    for result in replays["results"]:
        entry = by_profile.setdefault(result["case"]["profile"],
                                      {"cases": 0, "passed": 0, "replays": 0, "uncovered": 0})
        entry["cases"] += 1
        entry["passed"] += result["status"] == "pass"
        entry["replays"] += len(result["case"]["replays"]) if result["status"] == "pass" else 0
    for gap in replays["uncovered"]:
        by_profile.setdefault(gap["profile"], {"cases": 0, "passed": 0, "replays": 0,
                                               "uncovered": 0})["uncovered"] += 1
    for profile, entry in sorted(by_profile.items()):
        lines.append(f"| `{profile}` | {entry['passed']} of {entry['cases']} | {entry['replays']} | "
                     f"{entry['uncovered'] or '—'} |")
    lines += ["", f"**{totals['passed']} of {totals['cases']}** cases passed; "
              f"**{totals['passed_replays']} of {totals['replays']}** replays verified"
              + (f", {totals['uncovered_replays']} uncovered" if totals["uncovered_replays"] else "")
              + "."]
    if replays["uncovered"]:
        lines += ["", "A replay that cannot run is listed with its reason, never skipped:", ""]
        lines += [f"- `{gap['profile']}` {gap['exchange']}: {gap['reason']}"
                  for gap in replays["uncovered"]]
    lines += ["", "## Unit tests", ""]
    passed = units["run"] - units["failed"] - units["skipped"]
    lines += [f"**{passed} of {units['run']}** passed"
              + (f", {units['skipped']} skipped" if units["skipped"] else "")
              + (f", **{units['failed']} failed**" if units["failed"] else "")
              + f", in {', '.join(f'`{name}`' for name in units['files']) or 'no file'}.", "",
              "| Test class | Tests | Passed |", "|---|---|---|"]
    for cls, entry in sorted(units["classes"].items()):
        lines.append(f"| {cls} | {entry['tests']} | {entry['passed']} |")
    lines += ["", "## Contract", ""]
    if problems is None:
        lines.append("This television declares no surface yet, so there is no contract to check.")
    elif problems:
        lines.append(f"`tvemu --contract {platform_id} --check` found **{len(problems)}** "
                     "disagreements with the captures:")
        lines += [""] + [f"- {problem}" for problem in problems]
    else:
        lines.append(f"`tvemu --contract {platform_id} --check`: every curated claim agrees with "
                     "the captures.")
    return "\n".join(lines) + "\n"


def check() -> list[str]:
    """What is missing or out of date, for every catalogued television."""
    version = emulator_identity()["version"]
    problems = []
    for entry in catalogue_entries():
        path = page(entry.id)
        if not path.is_file():
            problems.append(f"{entry.id}: no test report; run `python tools/test_reports.py`")
            continue
        found = VERSION_LINE.search(path.read_text(encoding="utf-8"))
        if found is None or found["version"] != version:
            problems.append(f"{entry.id}: the test report is for "
                            f"{found['version'] if found else 'no version'}, not {version}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("platforms", nargs="*", help="platform ids (default: every one present)")
    parser.add_argument("--check", action="store_true",
                        help="fail when a catalogued television has no current report")
    args = parser.parse_args()
    if args.check:
        problems = check()
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1 if problems else 0
    identity = emulator_identity()
    if not identity["clean"]:
        print("Not written: src/ has uncommitted changes, so the version does not name what "
              "ran. Commit, then run again.", file=sys.stderr)
        return 1
    REPORTS.mkdir(parents=True, exist_ok=True)
    # Read before any test module runs: the test fixtures register stub platforms of their own.
    present = list(platform_ids())
    for platform_id in args.platforms or present:
        page(platform_id).write_text(render(platform_id, identity["version"]), encoding="utf-8")
        print(f"wrote {page(platform_id).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
